spring:
  application:
  name: chariot-inspector

  datasource:
    url: jdbc:mysql://localhost:3306/chariot_inspector
    username: user
    password: user_password

  jpa:
    hibernate:
      ddl-auto: none



server:
  port: 9001

  servlet:
    context-path: /chariot-inspector

