version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chariot_inspector_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chariot_inspector
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chariot_inspector_network

volumes:
  mysql_data:

networks:
  chariot_inspector_network:
    driver: bridge
